import { useState } from "react";

import { type NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { signIn, signOut, useSession } from "next-auth/react";

import { api } from "~/utils/api";

import { Input, FormGroup } from "~/components/form";
import useBuyCredits from "~/hooks/useBuyCredits";

const GeneratePage: NextPage = () => {
  const [form, setForm] = useState({
    prompt: "",
  });
  const [imageUrl, setImageUrl] = useState("");

  const session = useSession();
  const isLoggedIn = !!session.data;

  const buyCredits = useBuyCredits();

  function makeOnChangeFunction(key: string) {
    return function (e: React.ChangeEvent<HTMLInputElement>) {
      setForm((prev) => ({ ...prev, [key]: e.target.value }));
    };
  }

  const generateIcon = api.generate.generateIcon.useMutation({
    onSuccess(data) {
      console.log(`mutation finished, ${data.imageUrl}`);
      if (data.imageUrl) {
        setImageUrl(data.imageUrl);
      }
    },
  });

  function onSubmitPrompt(e: React.FormEvent) {
    e.preventDefault();

    generateIcon.mutate({ prompt: form.prompt });

    setForm({ prompt: "" });
  }

  return (
    <>
      <Head>
        <title>Suh Dude</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex min-h-screen flex-col items-center justify-center">
        <form onSubmit={onSubmitPrompt} className=" flex flex-col gap-5">
          <FormGroup>
            <label>Prompt</label>

            <Input
              value={form.prompt}
              onChange={makeOnChangeFunction("prompt")}
            ></Input>
          </FormGroup>

          <button className="rounded bg-blue-400 px-2 py-1 hover:bg-blue-600">
            Submit
          </button>
        </form>

        <Image src={imageUrl} alt="generated icon" height={150} width={150} />
      </main>
    </>
  );
};

export default GeneratePage;

export function Button(props: React.ComponentPropsWithoutRef<"button">) {
  return (
    <button
      {...props}
      className="rounded border-2 border-black px-2 py-1 transition hover:bg-black hover:text-white"
    >
      {props.children}
    </button>
  );
}
