import { Input, FormGroup } from "~/components/form";
import { api } from "~/utils/api";

import { useState } from "react";
import { type NextPage } from "next";
import Head from "next/head";

const GeneratePage: NextPage = () => {
  const [form, setForm] = useState({
    prompt: "",
  });

  function makeOnChangeFunction(key: string) {
    return function (e: React.ChangeEvent<HTMLInputElement>) {
      setForm((prev) => ({ ...prev, [key]: e.target.value }));
    };
  }

  const generateIcon = api.generate.generateIcon.useMutation({
    onSuccess(data) {
      console.log(`mutation finished, ${data.message}`);
    },
  });

  function onSubmitPrompt(e: React.FormEvent) {
    e.preventDefault();

    generateIcon.mutate({ prompt: form.prompt });
  }

  return (
    <>
      <Head>
        <title>Suh Dude</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex min-h-screen flex-col items-center justify-center">
        <form onSubmit={onSubmitPrompt} className=" flex flex-col gap-5">
          <FormGroup>
            <label>Prompt</label>

            <Input
              value={form.prompt}
              onChange={makeOnChangeFunction("prompt")}
            ></Input>
          </FormGroup>

          <button className="rounded bg-blue-400 px-2 py-1 hover:bg-blue-600">
            Submit
          </button>
        </form>
      </main>
    </>
  );
};

export default GeneratePage;
