import { type NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { HeaderButton } from "~/components/Header";

function HeroBanner() {
  return (
    <section className="mt-24 grid grid-cols-1 gap-12 sm:grid-cols-2">
      <div>
        <h1 className="text-4xl lg:text-6xl">
          Generate icons with the click of a button
        </h1>
        <br />

        <p className="text-xl">
          Fuck designers! Why pay $$$ to a human when a robot can do it for $.
        </p>
        <br />

        <HeaderButton>
          <Link href="/generate">Get Started</Link>
        </HeaderButton>
      </div>

      <Image
        src="/kings-landing.jpg"
        alt="King's Landing"
        width="400"
        height="300"
        className="order-first rounded sm:order-last"
      />
    </section>
  );
}

const HomePage: NextPage = () => {
  return (
    <>
      <Head>
        <title>aicons</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container mx-auto flex flex-col items-center justify-center px-4">
        <HeroBanner />
      </main>
    </>
  );
};

export default HomePage;
